#!/usr/bin/with-contenv bash

echo "*** GCloudCLI Installer ***"
echo "Checking if gcloud is installed"

if ! gcloud version &> /dev/null; then 
  apt-get update
  apt-get install apt-transport-https ca-certificates gnupg
  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  apt-get update
  apt-get install google-cloud-cli
else
  echo "Already Installed"
fi
